In [62]:
import pandas as pd
import numpy as np
from fbprophet import Prophet

In [63]:
columns=['ds','y']
df=pd.read_table('webMonth.csv', sep=',',header=None,names=columns )

In [64]:
len(df)

98

In [65]:
forecastDay=int(len(df)*0.1)

In [66]:
forecastDay

9

In [67]:
df['y'][-forecastDay:]=[1]*forecastDay

C:\Users\User\Anaconda3\envs\tensorflow35\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [68]:
print('[',[i for i in df['ds']],',',[i for i in df['y']],']')

[ ['2007-12-01', '2008-01-01', '2008-02-01', '2008-03-01', '2008-04-01', '2008-05-01', '2008-06-01', '2008-07-01', '2008-08-01', '2008-09-01', '2008-10-01', '2008-11-01', '2008-12-01', '2009-01-01', '2009-02-01', '2009-03-01', '2009-04-01', '2009-05-01', '2009-06-01', '2009-07-01', '2009-08-01', '2009-09-01', '2009-10-01', '2009-11-01', '2009-12-01', '2010-01-01', '2010-02-01', '2010-03-01', '2010-04-01', '2010-05-01', '2010-06-01', '2010-07-01', '2010-08-01', '2010-09-01', '2010-10-01', '2010-11-01', '2010-12-01', '2011-01-01', '2011-02-01', '2011-03-01', '2011-04-01', '2011-05-01', '2011-06-01', '2011-07-01', '2011-08-01', '2011-09-01', '2011-10-01', '2011-11-01', '2011-12-01', '2012-01-01', '2012-02-01', '2012-03-01', '2012-04-01', '2012-05-01', '2012-06-01', '2012-07-01', '2012-08-01', '2012-09-01', '2012-10-01', '2012-11-01', '2012-12-01', '2013-01-01', '2013-02-01', '2013-03-01', '2013-04-01', '2013-05-01', '2013-06-01', '2013-07-01', '2013-08-01', '2013-09-01', '2013-10-01', '2013-11-01', '2013-12-01', '2014-01-01', '2014-02-01', '2014-03-01', '2014-04-01', '2014-05-01', '2014-06-01', '2014-07-01', '2014-08-01', '2014-09-01', '2014-10-01', '2014-11-01', '2014-12-01', '2015-01-01', '2015-02-01', '2015-03-01', '2015-04-01', '2015-05-01', '2015-06-01', '2015-07-01', '2015-08-01', '2015-09-01', '2015-10-01', '2015-11-01', '2015-12-01', '2016-01-01'] , [4958.0, 8359.2999999999993, 12178.14286, 1735.5357140000001, 2178.5666670000001, 1424.419355, 1237.7142859999999, 1343.4545449999998, 2100.580645, 3135.5999999999999, 2644.517241, 2929.0, 2971.4838709999999, 4590.8709680000002, 2453.4642859999999, 1603.2903229999999, 1760.5, 1483.4838710000001, 1376.5333330000001, 1725.9354840000001, 2844.6451609999999, 5786.4615380000005, 6445.6428569999998, 6952.2142860000004, 7556.0322580000002, 13760.172409999999, 12469.23077, 2277.3225809999999, 2503.9666670000001, 1698.451613, 1425.5357140000001, 1848.6153850000001, 3838.3225810000004, 9605.4666670000006, 6985.6774189999996, 8732.5, 7899.0645159999995, 9540.9032260000004, 3907.1071430000002, 2085.8709680000002, 3015.5666670000001, 1886.193548, 1695.9000000000001, 3470.6451609999999, 4622.2258060000004, 9086.6896550000001, 6864.8666670000002, 7461.9666670000006, 7556.3103449999999, 19610.45161, 25008.793099999999, 24771.03226, 3943.3103450000003, 3136.3870969999998, 2406.8666670000002, 3127.6451609999999, 5017.7741939999996, 13273.733329999999, 9823.8064519999989, 7519.6666670000004, 9169.16129, 13726.903230000002, 4432.5, 2776.5161290000001, 2286.6333329999998, 1913.451613, 1650.9333329999999, 2040.0333329999999, 2734.0645159999999, 13740.266669999999, 10564.35484, 7608.3999999999996, 8706.1935480000011, 26366.56667, 24504.89286, 2169.0322579999997, 1879.0, 2449.5483870000003, 1487.9000000000001, 1903.580645, 3121.333333, 8773.6333329999998, 9429.2903230000011, 4370.5666670000001, 4122.7096770000007, 7644.7419349999991, 4147.0740740000001, 1799.7096770000001, 1405.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] ]

In [69]:
print([i for i in df['y']])

[4958.0, 8359.2999999999993, 12178.14286, 1735.5357140000001, 2178.5666670000001, 1424.419355, 1237.7142859999999, 1343.4545449999998, 2100.580645, 3135.5999999999999, 2644.517241, 2929.0, 2971.4838709999999, 4590.8709680000002, 2453.4642859999999, 1603.2903229999999, 1760.5, 1483.4838710000001, 1376.5333330000001, 1725.9354840000001, 2844.6451609999999, 5786.4615380000005, 6445.6428569999998, 6952.2142860000004, 7556.0322580000002, 13760.172409999999, 12469.23077, 2277.3225809999999, 2503.9666670000001, 1698.451613, 1425.5357140000001, 1848.6153850000001, 3838.3225810000004, 9605.4666670000006, 6985.6774189999996, 8732.5, 7899.0645159999995, 9540.9032260000004, 3907.1071430000002, 2085.8709680000002, 3015.5666670000001, 1886.193548, 1695.9000000000001, 3470.6451609999999, 4622.2258060000004, 9086.6896550000001, 6864.8666670000002, 7461.9666670000006, 7556.3103449999999, 19610.45161, 25008.793099999999, 24771.03226, 3943.3103450000003, 3136.3870969999998, 2406.8666670000002, 3127.6451609999999, 5017.7741939999996, 13273.733329999999, 9823.8064519999989, 7519.6666670000004, 9169.16129, 13726.903230000002, 4432.5, 2776.5161290000001, 2286.6333329999998, 1913.451613, 1650.9333329999999, 2040.0333329999999, 2734.0645159999999, 13740.266669999999, 10564.35484, 7608.3999999999996, 8706.1935480000011, 26366.56667, 24504.89286, 2169.0322579999997, 1879.0, 2449.5483870000003, 1487.9000000000001, 1903.580645, 3121.333333, 8773.6333329999998, 9429.2903230000011, 4370.5666670000001, 4122.7096770000007, 7644.7419349999991, 4147.0740740000001, 1799.7096770000001, 1405.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [70]:
len([ ['2007-12-01', '2008-01-01', '2008-02-01', '2008-03-01', '2008-04-01', '2008-05-01', '2008-06-01', '2008-07-01', '2008-08-01', '2008-09-01', '2008-10-01', '2008-11-01', '2008-12-01', '2009-01-01', '2009-02-01', '2009-03-01', '2009-04-01', '2009-05-01', '2009-06-01', '2009-07-01', '2009-08-01', '2009-09-01', '2009-10-01', '2009-11-01', '2009-12-01', '2010-01-01', '2010-02-01', '2010-03-01', '2010-04-01', '2010-05-01', '2010-06-01', '2010-07-01', '2010-01', '2010-09-01', '2010-10-01', '2010-11-01', '2010-12-01', '2011-01-01', '2011-02-01', '2011-03-01', '2011-04-01', '2011-05-01', '2011-06-01', '2011-07-01', '2011-08-01', '2011-09-01', '2011-10-01', '2011-11-01', '2011-12-01', '2012-01-01', '2012-02-01', '2012-03-01', '2012-04-01', '2012-05-01', '2012-06-01', '2012-07-01', '2012-08-01', '2012-09-01', '2012-10-01', '2012-11-01', '2012-12-01', '2013-01-01', '2013-02-01', '2013-03-01', '2013-04-01', '2013-05-01', '2013-06-01', '2013-07-01', '2013-08-01', '2013-09-01', '2013-10-01', '2013-11-01', '2013-12-01', '2014-01-01', '2014-02-01', '2014-03-01', '2014-04-01', '2014-05-01', '2014-06-01', '2014-07-01', '2014-08-01', '2014-09-01', '2014-10-01', '2014-11-01', '2014-12-01', '2015-01-01', '2015-02-01', '2015-03-01', '2015-04-01', '2015-05-01', '2015-06-01', '2015-07-01', '2015-08-01', '2015-09-01', '2015-10-01', '2015-11-01', '2015-12-01', '2016-01-01'] , [4958.0, 8359.2999999999993, 12178.14286, 1735.5357140000001, 2178.5666670000001, 1424.419355, 1237.7142859999999, 1343.4545449999998, 2100.580645, 3135.5999999999999, 2644.517241, 2929.0, 2971.4838709999999, 4590.8709680000002, 2453.4642859999999, 1603.2903229999999, 1760.5, 1483.4838710000001, 1376.5333330000001, 1725.9354840000001, 2844.6451609999999, 5786.4615380000005, 6445.6428569999998, 6952.2142860000004, 7556.0322580000002, 13760.172409999999, 12469.23077, 2277.3225809999999, 2503.9666670000001, 1698.451613, 1425.5357140000001, 1848.6153850000001, 3838.3225810000004, 9605.4666670000006, 6985.6774189999996, 8732.5, 7899.0645159999995, 9540.9032260000004, 3907.1071430000002, 2085.8709680000002, 3015.5666670000001, 1886.193548, 1695.9000000000001, 3470.6451609999999, 4622.2258060000004, 9086.6896550000001, 6864.8666670000002, 7461.9666670000006, 7556.3103449999999, 19610.45161, 25008.793099999999, 24771.03226, 3943.3103450000003, 3136.3870969999998, 2406.8666670000002, 3127.6451609999999, 5017.7741939999996, 13273.733329999999, 9823.8064519999989, 7519.6666670000004, 9169.16129, 13726.903230000002, 4432.5, 2776.5161290000001, 2286.6333329999998, 1913.451613, 1650.9333329999999, 2040.0333329999999, 2734.0645159999999, 13740.266669999999, 10564.35484, 7608.3999999999996, 8706.1935480000011, 26366.56667, 24504.89286, 2169.0322579999997, 1879.0, 2449.5483870000003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] ][1])

98