In [63]:
import pandas as pd
columns=['date','sales']

txs=pd.read_table('lstmPrac12.csv', sep=',',header=None,names=columns )

In [64]:
date=list(txs['date'][:101])

In [65]:
sales=list(txs['sales'][:101])

In [66]:
date=[str(i) for i in date]

In [67]:
dict={}

In [68]:
dict['Date']=date

In [69]:
dict['Data']=sales

In [70]:
dict

{'Data': [24924.5,
  46039.489999999998,
  41595.550000000003,
  19403.540000000001,
  21827.900000000001,
  21043.389999999999,
  22136.639999999999,
  26229.209999999999,
  57258.43,
  42960.910000000003,
  17596.959999999999,
  16145.35,
  16555.110000000001,
  17413.939999999999,
  18926.740000000002,
  14773.040000000001,
  15580.43,
  17558.09,
  16637.619999999999,
  16216.27,
  16328.719999999999,
  16333.139999999999,
  17688.759999999998,
  17150.84,
  15360.450000000001,
  15381.82,
  17508.41,
  15536.4,
  15740.129999999999,
  15793.870000000001,
  16241.780000000001,
  18194.740000000002,
  19354.23,
  18122.52,
  20094.189999999999,
  23388.029999999999,
  26978.34,
  25543.040000000001,
  38640.93,
  34238.879999999997,
  19549.389999999999,
  19552.84,
  18820.290000000001,
  22517.560000000001,
  31497.650000000001,
  44912.860000000001,
  55931.230000000003,
  19124.580000000002,
  15984.24,
  17359.700000000001,
  17341.470000000001,
  18461.18,
  21665.759999999998,
  37887.169999999998,
  46845.870000000003,
  19363.830000000002,
  20327.610000000001,
  21280.400000000001,
  20334.23,
  20881.099999999999,
  20398.09,
  23873.790000000001,
  28762.369999999999,
  50510.309999999998,
  41512.389999999999,
  20138.189999999999,
  17235.150000000001,
  15136.780000000001,
  15741.6,
  16434.150000000001,
  15883.52,
  14978.09,
  15682.809999999999,
  15363.5,
  16148.870000000001,
  15654.85,
  15766.6,
  15922.41,
  15295.549999999999,
  14539.790000000001,
  14689.24,
  14537.370000000001,
  15277.27,
  17746.68,
  18535.48,
  17859.299999999999,
  18337.68,
  20797.580000000002,
  23077.549999999999,
  23351.799999999999,
  31579.900000000001,
  39886.059999999998,
  18689.540000000001,
  19050.66,
  20911.25,
  25293.490000000002,
  33305.919999999998,
  45773.029999999999,
  46788.75,
  23350.880000000001,
  16567.689999999999],
 'Date': ['2010-02-05',
  '2010-02-12',
  '2010-02-19',
  '2010-02-26',
  '2010-03-05',
  '2010-03-12',
  '2010-03-19',
  '2010-03-26',
  '2010-04-02',
  '2010-04-09',
  '2010-04-16',
  '2010-04-23',
  '2010-04-30',
  '2010-05-07',
  '2010-05-14',
  '2010-05-21',
  '2010-05-28',
  '2010-06-04',
  '2010-06-11',
  '2010-06-18',
  '2010-06-25',
  '2010-07-02',
  '2010-07-09',
  '2010-07-16',
  '2010-07-23',
  '2010-07-30',
  '2010-08-06',
  '2010-08-13',
  '2010-08-20',
  '2010-08-27',
  '2010-09-03',
  '2010-09-10',
  '2010-09-17',
  '2010-09-24',
  '2010-10-01',
  '2010-10-08',
  '2010-10-15',
  '2010-10-22',
  '2010-10-29',
  '2010-11-05',
  '2010-11-12',
  '2010-11-19',
  '2010-11-26',
  '2010-12-03',
  '2010-12-10',
  '2010-12-17',
  '2010-12-24',
  '2010-12-31',
  '2011-01-07',
  '2011-01-14',
  '2011-01-21',
  '2011-01-28',
  '2011-02-04',
  '2011-02-11',
  '2011-02-18',
  '2011-02-25',
  '2011-03-04',
  '2011-03-11',
  '2011-03-18',
  '2011-03-25',
  '2011-04-01',
  '2011-04-08',
  '2011-04-15',
  '2011-04-22',
  '2011-04-29',
  '2011-05-06',
  '2011-05-13',
  '2011-05-20',
  '2011-05-27',
  '2011-06-03',
  '2011-06-10',
  '2011-06-17',
  '2011-06-24',
  '2011-07-01',
  '2011-07-08',
  '2011-07-15',
  '2011-07-22',
  '2011-07-29',
  '2011-08-05',
  '2011-08-12',
  '2011-08-19',
  '2011-08-26',
  '2011-09-02',
  '2011-09-09',
  '2011-09-16',
  '2011-09-23',
  '2011-09-30',
  '2011-10-07',
  '2011-10-14',
  '2011-10-21',
  '2011-10-28',
  '2011-11-04',
  '2011-11-11',
  '2011-11-18',
  '2011-11-25',
  '2011-12-02',
  '2011-12-09',
  '2011-12-16',
  '2011-12-23',
  '2011-12-30',
  '2012-01-06']}

In [71]:
[16217.607056630432, 13352.359930651126, 14611.038388640642, 19996.038016666582, 28741.567900311176, 35391.69017703088, 33410.60568000184, 25774.984726151557, 19819.874680670404, 18227.407988362193, 20629.16344488644, 25358.436620204768, 29128.43476525707, 29605.25397275583, 27816.732163299013, 25485.462625051034, 22828.646142460093, 19671.30931898292, 16760.724776985724, 15121.895834173281, 15010.581717469231, 15753.321236833079, 16187.778458298064, 15797.105801266274, 15243.557522508514, 15304.771740126136, 15907.55314354267, 16258.077474842868, 15853.025645395654, 15147.642878953882, 14827.85286742366, 14955.07614562469, 15086.498181601144, 15063.846352094137, 15380.74862872602, 16523.32389227922, 18129.68086450395, 19071.92772169003, 19063.698544425108, 19643.11205742312, 22744.271853462506, 28574.816920748188]

[16217.607056630432,
 13352.359930651126,
 14611.038388640642,
 19996.038016666582,
 28741.567900311176,
 35391.69017703088,
 33410.60568000184,
 25774.984726151557,
 19819.874680670404,
 18227.407988362193,
 20629.16344488644,
 25358.436620204768,
 29128.43476525707,
 29605.25397275583,
 27816.732163299013,
 25485.462625051034,
 22828.646142460093,
 19671.30931898292,
 16760.724776985724,
 15121.895834173281,
 15010.581717469231,
 15753.321236833079,
 16187.778458298064,
 15797.105801266274,
 15243.557522508514,
 15304.771740126136,
 15907.55314354267,
 16258.077474842868,
 15853.025645395654,
 15147.642878953882,
 14827.85286742366,
 14955.07614562469,
 15086.498181601144,
 15063.846352094137,
 15380.74862872602,
 16523.32389227922,
 18129.68086450395,
 19071.92772169003,
 19063.698544425108,
 19643.11205742312,
 22744.271853462506,
 28574.816920748188]